// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'package:foodmandu/models/item.dart';
import 'package:foodmandu/models/restaurant.dart';

class Food {
  final String name;
  final String image;
  final Restaurant restaurant;
  Food({required this.name, required this.image, required this.restaurant});
}

List<Food> foods = [
  Food(
    name: 'Pizza',
    image: 'assets/foodimages/pizza.png',
    restaurant: Restaurant(
        images: [
          'assets/restaurantimages/woodfire.jpeg',
          'assets/restaurantimages/roadhouse.jpeg',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/elixir.png',
          'assets/restaurantimages/poppizza.png',
          'assets/restaurantimages/piano.png',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/baardali.png',
          'assets/restaurantimages/peros.jpeg',
          'assets/restaurantimages/octave.jpeg',
        ],
        name: [
          'Wood Fire House Pizzeria',
          'Roadhouse Pizza- Maharajgunj',
          'Emilio\'s Pizza',
          'Elixir Cafe',
          'Pop in Pizza',
          'Pianno Piano',
          'Pizza inn',
          'Baardali Cafe',
          'Peros Pizza by Trisara',
          'Octave Restro'
        ],
        location: [
          'Machapokhari',
          'Maharagunj',
          'Bansbari',
          'Nayabazaar',
          'Baluwatar',
          'Lazimpat',
          'Dhumbarahi',
          'Thamel',
          'Lazimpat',
          'DurbarMarg'
        ],
        rating: [
          '4.00',
          '4.31',
          '4.13',
          '3.12',
          '4.56',
          '5.00',
          '4.9',
          '4.2',
          '4.4',
          '5.00'
        ],
        deliverytime: [
          '12:30 PM to 8:30 PM',
          '12:00 PM to 9:30 PM',
          '2:00 PM to 7:30 PM',
          '9:10 PM to 7:30 PM',
          '2:40 PM to 9:30 PM',
          '12:50 PM to 10:30 PM',
          '2:70 PM to 11:30 PM',
          '1:90 PM to 12:30 AM',
          '12:70 PM to 4:30 PM',
          '6:40 PM to 8:30 PM',
        ],
        fooditem: Fooditem(name: [
          'Chicken Pepperoni ',
          'Classic Pizza Margarita ',
          'Sicilian pizza',
          'Farmhouse Pizza ',
          'Oriental Veg Pizza ',
          'Mixed Pizza ',
          'Mushroom Pizza ',
          'Cheese Pizza ',
          'Panner Tikka Pizza ',
          'Pizza Ortolana '
        ], price: [
          'Rs.560',
          'Rs.860',
          'Rs.800',
          'Rs.1200',
          'Rs.900',
          'Rs.500',
          'Rs.600',
          'Rs.660',
          'Rs.750',
          'Rs.850'
        ], foodpictures: [
          'assets/spotlight/biryani.jpg',
          'assets/spotlight/momo.jpg',
          'assets/exclusiveimages/hotdog.jpg',
          'assets/spotlight/pizza.jpg',
          'assets/momos/turkish.png',
          'assets/spotlight/smoke.jpg',
          'assets/spotlight/whitepizza.jpg',
          'assets/momos/tandoori.jpg',
          'assets/exclusiveimages/letrio.jpg',
          'assets/exclusiveimages/sushi.jpg',
        ], foodpicturesname: [
          'Multi Cuisine',
          'Momo',
          'Multi Cuisine',
          'Multi Cuisine | Breakfast',
          'Turkish',
          'Indian | Halal',
          'Fast Food',
          'Nepali | Indian',
          'American',
          'Japanese | Multicuisine',
        ])),
  ),
  Food(
    name: 'Momos',
    image: 'assets/foodimages/momo.png',
    restaurant: Restaurant(
        images: [
          'assets/restaurantimages/woodfire.jpeg',
          'assets/restaurantimages/roadhouse.jpeg',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/elixir.png',
          'assets/restaurantimages/poppizza.png',
          'assets/restaurantimages/piano.png',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/baardali.png',
          'assets/restaurantimages/peros.jpeg',
          'assets/restaurantimages/octave.jpeg',
        ],
        name: [
          'Wood Fire House Pizzeria',
          'Roadhouse Pizza- Maharajgunj',
          'Emilio\'s Pizza',
          'Elixir Cafe',
          'Pop in Pizza',
          'Pianno Piano',
          'Pizza inn',
          'Baardali Cafe',
          'Peros Pizza by Trisara',
          'Octave Restro'
        ],
        location: [
          'Machapokhari',
          'Maharagunj',
          'Bansbari',
          'Nayabazaar',
          'Baluwatar',
          'Lazimpat',
          'Dhumbarahi',
          'Thamel',
          'Lazimpat',
          'DurbarMarg'
        ],
        rating: [
          '4.00',
          '4.31',
          '4.13',
          '3.12',
          '4.56',
          '5.00',
          '4.9',
          '4.2',
          '4.4',
          '5.00'
        ],
        deliverytime: [
          '12:30 PM to 8:30 PM',
          '12:00 PM to 9:30 PM',
          '2:00 PM to 7:30 PM',
          '9:10 PM to 7:30 PM',
          '2:40 PM to 9:30 PM',
          '12:50 PM to 10:30 PM',
          '2:70 PM to 11:30 PM',
          '1:90 PM to 12:30 AM',
          '12:70 PM to 4:30 PM',
          '6:40 PM to 8:30 PM',
        ],
        fooditem: Fooditem(foodpicturesname: [
          'Multi Cuisine',
          'Momo',
          'Multi Cuisine',
          'Multi Cuisine | Breakfast',
          'Turkish',
          'Indian | Halal',
          'Fast Food',
          'Nepali | Indian',
          'American',
          'Japanese | Multicuisine',
        ], name: [
          'Chicken Pepperoni ',
          'Classic Pizza Margarita ',
          'Sicilian pizza',
          'Farmhouse Pizza ',
          'Oriental Veg Pizza ',
          'Mixed Pizza ',
          'Mushroom Pizza ',
          'Cheese Pizza ',
          'Panner Tikka Pizza ',
          'Pizza Ortolana '
        ], price: [
          'Rs.560',
          'Rs.860',
          'Rs.800',
          'Rs.1200',
          'Rs.900',
          'Rs.500',
          'Rs.600',
          'Rs.660',
          'Rs.750',
          'Rs.850'
        ], foodpictures: [
          'assets/spotlight/biryani.jpg',
          'assets/spotlight/momo.jpg',
          'assets/exclusiveimages/hotdog.jpg',
          'assets/spotlight/pizza.jpg',
          'assets/momos/turkish.png',
          'assets/spotlight/smoke.jpg',
          'assets/spotlight/whitepizza.jpg',
          'assets/momos/tandoori.jpg',
          'assets/exclusiveimages/letrio.jpg',
          'assets/exclusiveimages/sushi.jpg',
        ])),
  ),
  Food(
    name: 'Fried Chicken',
    image: 'assets/foodimages/friedchicken.png',
    restaurant: Restaurant(
        images: [
          'assets/restaurantimages/woodfire.jpeg',
          'assets/restaurantimages/roadhouse.jpeg',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/elixir.png',
          'assets/restaurantimages/poppizza.png',
          'assets/restaurantimages/piano.png',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/baardali.png',
          'assets/restaurantimages/peros.jpeg',
          'assets/restaurantimages/octave.jpeg',
        ],
        name: [
          'Wood Fire House Pizzeria',
          'Roadhouse Pizza- Maharajgunj',
          'Emilio\'s Pizza',
          'Elixir Cafe',
          'Pop in Pizza',
          'Pianno Piano',
          'Pizza inn',
          'Baardali Cafe',
          'Peros Pizza by Trisara',
          'Octave Restro'
        ],
        location: [
          'Machapokhari',
          'Maharagunj',
          'Bansbari',
          'Nayabazaar',
          'Baluwatar',
          'Lazimpat',
          'Dhumbarahi',
          'Thamel',
          'Lazimpat',
          'DurbarMarg'
        ],
        rating: [
          '4.00',
          '4.31',
          '4.13',
          '3.12',
          '4.56',
          '5.00',
          '4.9',
          '4.2',
          '4.4',
          '5.00'
        ],
        deliverytime: [
          '12:30 PM to 8:30 PM',
          '12:00 PM to 9:30 PM',
          '2:00 PM to 7:30 PM',
          '9:10 PM to 7:30 PM',
          '2:40 PM to 9:30 PM',
          '12:50 PM to 10:30 PM',
          '2:70 PM to 11:30 PM',
          '1:90 PM to 12:30 AM',
          '12:70 PM to 4:30 PM',
          '6:40 PM to 8:30 PM',
        ],
        fooditem: Fooditem(foodpicturesname: [
          'Multi Cuisine',
          'Momo',
          'Multi Cuisine',
          'Multi Cuisine | Breakfast',
          'Turkish',
          'Indian | Halal',
          'Fast Food',
          'Nepali | Indian',
          'American',
          'Japanese | Multicuisine',
        ], name: [
          'Chicken Pepperoni ',
          'Classic Pizza Margarita ',
          'Sicilian pizza',
          'Farmhouse Pizza ',
          'Oriental Veg Pizza ',
          'Mixed Pizza ',
          'Mushroom Pizza ',
          'Cheese Pizza ',
          'Panner Tikka Pizza ',
          'Pizza Ortolana '
        ], foodpictures: [
          'assets/spotlight/biryani.jpg',
          'assets/spotlight/momo.jpg',
          'assets/exclusiveimages/hotdog.jpg',
          'assets/spotlight/pizza.jpg',
          'assets/momos/turkish.png',
          'assets/spotlight/smoke.jpg',
          'assets/spotlight/whitepizza.jpg',
          'assets/momos/tandoori.jpg',
          'assets/exclusiveimages/letrio.jpg',
          'assets/exclusiveimages/sushi.jpg',
        ], price: [
          'Rs.560',
          'Rs.860',
          'Rs.800',
          'Rs.1200',
          'Rs.900',
          'Rs.500',
          'Rs.600',
          'Rs.660',
          'Rs.750',
          'Rs.850'
        ])),
  ),
  Food(
    name: 'Biryani',
    image: 'assets/foodimages/biryani.png',
    restaurant: Restaurant(
        images: [
          'assets/restaurantimages/woodfire.jpeg',
          'assets/restaurantimages/roadhouse.jpeg',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/elixir.png',
          'assets/restaurantimages/poppizza.png',
          'assets/restaurantimages/piano.png',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/baardali.png',
          'assets/restaurantimages/peros.jpeg',
          'assets/restaurantimages/octave.jpeg',
        ],
        name: [
          'Wood Fire House Pizzeria',
          'Roadhouse Pizza- Maharajgunj',
          'Emilio\'s Pizza',
          'Elixir Cafe',
          'Pop in Pizza',
          'Pianno Piano',
          'Pizza inn',
          'Baardali Cafe',
          'Peros Pizza by Trisara',
          'Octave Restro'
        ],
        location: [
          'Machapokhari',
          'Maharagunj',
          'Bansbari',
          'Nayabazaar',
          'Baluwatar',
          'Lazimpat',
          'Dhumbarahi',
          'Thamel',
          'Lazimpat',
          'DurbarMarg'
        ],
        rating: [
          '4.00',
          '4.31',
          '4.13',
          '3.12',
          '4.56',
          '5.00',
          '4.9',
          '4.2',
          '4.4',
          '5.00'
        ],
        deliverytime: [
          '12:30 PM to 8:30 PM',
          '12:00 PM to 9:30 PM',
          '2:00 PM to 7:30 PM',
          '9:10 PM to 7:30 PM',
          '2:40 PM to 9:30 PM',
          '12:50 PM to 10:30 PM',
          '2:70 PM to 11:30 PM',
          '1:90 PM to 12:30 AM',
          '12:70 PM to 4:30 PM',
          '6:40 PM to 8:30 PM',
        ],
        fooditem: Fooditem(foodpicturesname: [
          'Multi Cuisine',
          'Momo',
          'Multi Cuisine',
          'Multi Cuisine | Breakfast',
          'Turkish',
          'Indian | Halal',
          'Fast Food',
          'Nepali | Indian',
          'American',
          'Japanese | Multicuisine',
        ], foodpictures: [
          'assets/spotlight/biryani.jpg',
          'assets/spotlight/momo.jpg',
          'assets/exclusiveimages/hotdog.jpg',
          'assets/spotlight/pizza.jpg',
          'assets/momos/turkish.png',
          'assets/spotlight/smoke.jpg',
          'assets/spotlight/whitepizza.jpg',
          'assets/momos/tandoori.jpg',
          'assets/exclusiveimages/letrio.jpg',
          'assets/exclusiveimages/sushi.jpg',
        ], name: [
          'Chicken Pepperoni ',
          'Classic Pizza Margarita ',
          'Sicilian pizza',
          'Farmhouse Pizza ',
          'Oriental Veg Pizza ',
          'Mixed Pizza ',
          'Mushroom Pizza ',
          'Cheese Pizza ',
          'Panner Tikka Pizza ',
          'Pizza Ortolana '
        ], price: [
          'Rs.560',
          'Rs.860',
          'Rs.800',
          'Rs.1200',
          'Rs.900',
          'Rs.500',
          'Rs.600',
          'Rs.660',
          'Rs.750',
          'Rs.850'
        ])),
  ),
  Food(
    name: 'Burger',
    image: 'assets/foodimages/burger.png',
    restaurant: Restaurant(
        images: [
          'assets/restaurantimages/woodfire.jpeg',
          'assets/restaurantimages/roadhouse.jpeg',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/elixir.png',
          'assets/restaurantimages/poppizza.png',
          'assets/restaurantimages/piano.png',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/baardali.png',
          'assets/restaurantimages/peros.jpeg',
          'assets/restaurantimages/octave.jpeg',
        ],
        name: [
          'Wood Fire House Pizzeria',
          'Roadhouse Pizza- Maharajgunj',
          'Emilio\'s Pizza',
          'Elixir Cafe',
          'Pop in Pizza',
          'Pianno Piano',
          'Pizza inn',
          'Baardali Cafe',
          'Peros Pizza by Trisara',
          'Octave Restro'
        ],
        location: [
          'Machapokhari',
          'Maharagunj',
          'Bansbari',
          'Nayabazaar',
          'Baluwatar',
          'Lazimpat',
          'Dhumbarahi',
          'Thamel',
          'Lazimpat',
          'DurbarMarg'
        ],
        rating: [
          '4.00',
          '4.31',
          '4.13',
          '3.12',
          '4.56',
          '5.00',
          '4.9',
          '4.2',
          '4.4',
          '5.00'
        ],
        deliverytime: [
          '12:30 PM to 8:30 PM',
          '12:00 PM to 9:30 PM',
          '2:00 PM to 7:30 PM',
          '9:10 PM to 7:30 PM',
          '2:40 PM to 9:30 PM',
          '12:50 PM to 10:30 PM',
          '2:70 PM to 11:30 PM',
          '1:90 PM to 12:30 AM',
          '12:70 PM to 4:30 PM',
          '6:40 PM to 8:30 PM',
        ],
        fooditem: Fooditem(foodpicturesname: [
          'Multi Cuisine',
          'Momo',
          'Multi Cuisine',
          'Multi Cuisine | Breakfast',
          'Turkish',
          'Indian | Halal',
          'Fast Food',
          'Nepali | Indian',
          'American',
          'Japanese | Multicuisine',
        ], foodpictures: [
          'assets/spotlight/biryani.jpg',
          'assets/spotlight/momo.jpg',
          'assets/exclusiveimages/hotdog.jpg',
          'assets/spotlight/pizza.jpg',
          'assets/momos/turkish.png',
          'assets/spotlight/smoke.jpg',
          'assets/spotlight/whitepizza.jpg',
          'assets/momos/tandoori.jpg',
          'assets/exclusiveimages/letrio.jpg',
          'assets/exclusiveimages/sushi.jpg',
        ], name: [
          'Chicken Pepperoni ',
          'Classic Pizza Margarita ',
          'Sicilian pizza',
          'Farmhouse Pizza ',
          'Oriental Veg Pizza ',
          'Mixed Pizza ',
          'Mushroom Pizza ',
          'Cheese Pizza ',
          'Panner Tikka Pizza ',
          'Pizza Ortolana '
        ], price: [
          'Rs.560',
          'Rs.860',
          'Rs.800',
          'Rs.1200',
          'Rs.900',
          'Rs.500',
          'Rs.600',
          'Rs.660',
          'Rs.750',
          'Rs.850'
        ])),
  ),
  Food(
    name: 'Bakeries',
    image: 'assets/foodimages/cake.png',
    restaurant: Restaurant(
        images: [
          'assets/restaurantimages/woodfire.jpeg',
          'assets/restaurantimages/roadhouse.jpeg',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/elixir.png',
          'assets/restaurantimages/poppizza.png',
          'assets/restaurantimages/piano.png',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/baardali.png',
          'assets/restaurantimages/peros.jpeg',
          'assets/restaurantimages/octave.jpeg',
        ],
        name: [
          'Wood Fire House Pizzeria',
          'Roadhouse Pizza- Maharajgunj',
          'Emilio\'s Pizza',
          'Elixir Cafe',
          'Pop in Pizza',
          'Pianno Piano',
          'Pizza inn',
          'Baardali Cafe',
          'Peros Pizza by Trisara',
          'Octave Restro'
        ],
        location: [
          'Machapokhari',
          'Maharagunj',
          'Bansbari',
          'Nayabazaar',
          'Baluwatar',
          'Lazimpat',
          'Dhumbarahi',
          'Thamel',
          'Lazimpat',
          'DurbarMarg'
        ],
        rating: [
          '4.00',
          '4.31',
          '4.13',
          '3.12',
          '4.56',
          '5.00',
          '4.9',
          '4.2',
          '4.4',
          '5.00'
        ],
        deliverytime: [
          '12:30 PM to 8:30 PM',
          '12:00 PM to 9:30 PM',
          '2:00 PM to 7:30 PM',
          '9:10 PM to 7:30 PM',
          '2:40 PM to 9:30 PM',
          '12:50 PM to 10:30 PM',
          '2:70 PM to 11:30 PM',
          '1:90 PM to 12:30 AM',
          '12:70 PM to 4:30 PM',
          '6:40 PM to 8:30 PM',
        ],
        fooditem: Fooditem(foodpicturesname: [
          'Multi Cuisine',
          'Momo',
          'Multi Cuisine',
          'Multi Cuisine | Breakfast',
          'Turkish',
          'Indian | Halal',
          'Fast Food',
          'Nepali | Indian',
          'American',
          'Japanese | Multicuisine',
        ], foodpictures: [
          'assets/spotlight/biryani.jpg',
          'assets/spotlight/momo.jpg',
          'assets/exclusiveimages/hotdog.jpg',
          'assets/spotlight/pizza.jpg',
          'assets/momos/turkish.png',
          'assets/spotlight/smoke.jpg',
          'assets/spotlight/whitepizza.jpg',
          'assets/momos/tandoori.jpg',
          'assets/exclusiveimages/letrio.jpg',
          'assets/exclusiveimages/sushi.jpg',
        ], name: [
          'Chicken Pepperoni ',
          'Classic Pizza Margarita ',
          'Sicilian pizza',
          'Farmhouse Pizza ',
          'Oriental Veg Pizza ',
          'Mixed Pizza ',
          'Mushroom Pizza ',
          'Cheese Pizza ',
          'Panner Tikka Pizza ',
          'Pizza Ortolana '
        ], price: [
          'Rs.560',
          'Rs.860',
          'Rs.800',
          'Rs.1200',
          'Rs.900',
          'Rs.500',
          'Rs.600',
          'Rs.660',
          'Rs.750',
          'Rs.850'
        ])),
  ),
  Food(
    name: 'Liquors',
    image: 'assets/foodimages/alcohol.png',
    restaurant: Restaurant(
        images: [
          'assets/restaurantimages/woodfire.jpeg',
          'assets/restaurantimages/roadhouse.jpeg',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/elixir.png',
          'assets/restaurantimages/poppizza.png',
          'assets/restaurantimages/piano.png',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/baardali.png',
          'assets/restaurantimages/peros.jpeg',
          'assets/restaurantimages/octave.jpeg',
        ],
        name: [
          'Wood Fire House Pizzeria',
          'Roadhouse Pizza- Maharajgunj',
          'Emilio\'s Pizza',
          'Elixir Cafe',
          'Pop in Pizza',
          'Pianno Piano',
          'Pizza inn',
          'Baardali Cafe',
          'Peros Pizza by Trisara',
          'Octave Restro'
        ],
        location: [
          'Machapokhari',
          'Maharagunj',
          'Bansbari',
          'Nayabazaar',
          'Baluwatar',
          'Lazimpat',
          'Dhumbarahi',
          'Thamel',
          'Lazimpat',
          'DurbarMarg'
        ],
        rating: [
          '4.00',
          '4.31',
          '4.13',
          '3.12',
          '4.56',
          '5.00',
          '4.9',
          '4.2',
          '4.4',
          '5.00'
        ],
        deliverytime: [
          '12:30 PM to 8:30 PM',
          '12:00 PM to 9:30 PM',
          '2:00 PM to 7:30 PM',
          '9:10 PM to 7:30 PM',
          '2:40 PM to 9:30 PM',
          '12:50 PM to 10:30 PM',
          '2:70 PM to 11:30 PM',
          '1:90 PM to 12:30 AM',
          '12:70 PM to 4:30 PM',
          '6:40 PM to 8:30 PM',
        ],
        fooditem: Fooditem(foodpicturesname: [
          'Multi Cuisine',
          'Momo',
          'Multi Cuisine',
          'Multi Cuisine | Breakfast',
          'Turkish',
          'Indian | Halal',
          'Fast Food',
          'Nepali | Indian',
          'American',
          'Japanese | Multicuisine',
        ], foodpictures: [
          'assets/spotlight/biryani.jpg',
          'assets/spotlight/momo.jpg',
          'assets/exclusiveimages/hotdog.jpg',
          'assets/spotlight/pizza.jpg',
          'assets/momos/turkish.png',
          'assets/spotlight/smoke.jpg',
          'assets/spotlight/whitepizza.jpg',
          'assets/momos/tandoori.jpg',
          'assets/exclusiveimages/letrio.jpg',
          'assets/exclusiveimages/sushi.jpg',
        ], name: [
          'Chicken Pepperoni ',
          'Classic Pizza Margarita ',
          'Sicilian pizza',
          'Farmhouse Pizza ',
          'Oriental Veg Pizza ',
          'Mixed Pizza ',
          'Mushroom Pizza ',
          'Cheese Pizza ',
          'Panner Tikka Pizza ',
          'Pizza Ortolana '
        ], price: [
          'Rs.560',
          'Rs.860',
          'Rs.800',
          'Rs.1200',
          'Rs.900',
          'Rs.500',
          'Rs.600',
          'Rs.660',
          'Rs.750',
          'Rs.850'
        ])),
  ),
  Food(
    name: 'Vegeterian',
    image: 'assets/foodimages/veges.png',
    restaurant: Restaurant(
        images: [
          'assets/restaurantimages/woodfire.jpeg',
          'assets/restaurantimages/roadhouse.jpeg',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/elixir.png',
          'assets/restaurantimages/poppizza.png',
          'assets/restaurantimages/piano.png',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/baardali.png',
          'assets/restaurantimages/peros.jpeg',
          'assets/restaurantimages/octave.jpeg',
        ],
        name: [
          'Wood Fire House Pizzeria',
          'Roadhouse Pizza- Maharajgunj',
          'Emilio\'s Pizza',
          'Elixir Cafe',
          'Pop in Pizza',
          'Pianno Piano',
          'Pizza inn',
          'Baardali Cafe',
          'Peros Pizza by Trisara',
          'Octave Restro'
        ],
        location: [
          'Machapokhari',
          'Maharagunj',
          'Bansbari',
          'Nayabazaar',
          'Baluwatar',
          'Lazimpat',
          'Dhumbarahi',
          'Thamel',
          'Lazimpat',
          'DurbarMarg'
        ],
        rating: [
          '4.00',
          '4.31',
          '4.13',
          '3.12',
          '4.56',
          '5.00',
          '4.9',
          '4.2',
          '4.4',
          '5.00'
        ],
        deliverytime: [
          '12:30 PM to 8:30 PM',
          '12:00 PM to 9:30 PM',
          '2:00 PM to 7:30 PM',
          '9:10 PM to 7:30 PM',
          '2:40 PM to 9:30 PM',
          '12:50 PM to 10:30 PM',
          '2:70 PM to 11:30 PM',
          '1:90 PM to 12:30 AM',
          '12:70 PM to 4:30 PM',
          '6:40 PM to 8:30 PM',
        ],
        fooditem: Fooditem(foodpicturesname: [
          'Multi Cuisine',
          'Momo',
          'Multi Cuisine',
          'Multi Cuisine | Breakfast',
          'Turkish',
          'Indian | Halal',
          'Fast Food',
          'Nepali | Indian',
          'American',
          'Japanese | Multicuisine',
        ], foodpictures: [
          'assets/spotlight/biryani.jpg',
          'assets/spotlight/momo.jpg',
          'assets/exclusiveimages/hotdog.jpg',
          'assets/spotlight/pizza.jpg',
          'assets/momos/turkish.png',
          'assets/spotlight/smoke.jpg',
          'assets/spotlight/whitepizza.jpg',
          'assets/momos/tandoori.jpg',
          'assets/exclusiveimages/letrio.jpg',
          'assets/exclusiveimages/sushi.jpg',
        ], name: [
          'Chicken Pepperoni ',
          'Classic Pizza Margarita ',
          'Sicilian pizza',
          'Farmhouse Pizza ',
          'Oriental Veg Pizza ',
          'Mixed Pizza ',
          'Mushroom Pizza ',
          'Cheese Pizza ',
          'Panner Tikka Pizza ',
          'Pizza Ortolana '
        ], price: [
          'Rs.560',
          'Rs.860',
          'Rs.800',
          'Rs.1200',
          'Rs.900',
          'Rs.500',
          'Rs.600',
          'Rs.660',
          'Rs.750',
          'Rs.850'
        ])),
  ),
  Food(
    name: 'Refreshment',
    image: 'assets/foodimages/mojito.png',
    restaurant: Restaurant(
        images: [
          'assets/restaurantimages/woodfire.jpeg',
          'assets/restaurantimages/roadhouse.jpeg',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/elixir.png',
          'assets/restaurantimages/poppizza.png',
          'assets/restaurantimages/piano.png',
          'assets/restaurantimages/inn.png',
          'assets/restaurantimages/baardali.png',
          'assets/restaurantimages/peros.jpeg',
          'assets/restaurantimages/octave.jpeg',
        ],
        name: [
          'Wood Fire House Pizzeria',
          'Roadhouse Pizza- Maharajgunj',
          'Emilio\'s Pizza',
          'Elixir Cafe',
          'Pop in Pizza',
          'Pianno Piano',
          'Pizza inn',
          'Baardali Cafe',
          'Peros Pizza by Trisara',
          'Octave Restro'
        ],
        location: [
          'Machapokhari',
          'Maharagunj',
          'Bansbari',
          'Nayabazaar',
          'Baluwatar',
          'Lazimpat',
          'Dhumbarahi',
          'Thamel',
          'Lazimpat',
          'DurbarMarg'
        ],
        rating: [
          '4.00',
          '4.31',
          '4.13',
          '3.12',
          '4.56',
          '5.00',
          '4.9',
          '4.2',
          '4.4',
          '5.00'
        ],
        deliverytime: [
          '12:30 PM to 8:30 PM',
          '12:00 PM to 9:30 PM',
          '2:00 PM to 7:30 PM',
          '9:10 PM to 7:30 PM',
          '2:40 PM to 9:30 PM',
          '12:50 PM to 10:30 PM',
          '2:70 PM to 11:30 PM',
          '1:90 PM to 12:30 AM',
          '12:70 PM to 4:30 PM',
          '6:40 PM to 8:30 PM',
        ],
        fooditem: Fooditem(foodpicturesname: [
          'Multi Cuisine',
          'Momo',
          'Multi Cuisine',
          'Multi Cuisine | Breakfast',
          'Turkish',
          'Indian | Halal',
          'Fast Food',
          'Nepali | Indian',
          'American',
          'Japanese | Multicuisine',
        ], foodpictures: [
          'assets/spotlight/biryani.jpg',
          'assets/spotlight/momo.jpg',
          'assets/exclusiveimages/hotdog.jpg',
          'assets/spotlight/pizza.jpg',
          'assets/momos/turkish.png',
          'assets/spotlight/smoke.jpg',
          'assets/spotlight/whitepizza.jpg',
          'assets/momos/tandoori.jpg',
          'assets/exclusiveimages/letrio.jpg',
          'assets/exclusiveimages/sushi.jpg',
        ], name: [
          'Chicken Pepperoni ',
          'Classic Pizza Margarita ',
          'Sicilian pizza',
          'Farmhouse Pizza ',
          'Oriental Veg Pizza ',
          'Mixed Pizza ',
          'Mushroom Pizza ',
          'Cheese Pizza ',
          'Panner Tikka Pizza ',
          'Pizza Ortolana '
        ], price: [
          'Rs.560',
          'Rs.860',
          'Rs.800',
          'Rs.1200',
          'Rs.900',
          'Rs.500',
          'Rs.600',
          'Rs.660',
          'Rs.750',
          'Rs.850'
        ])),
  ),
];
