// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRwSaFUWn9qHMjcZmU_-aHAhyi88SC35I',
    appId: '1:546013665087:web:f89d26a95c22f2395ba58a',
    messagingSenderId: '546013665087',
    projectId: 'foodmandu-a1c94',
    authDomain: 'foodmandu-a1c94.firebaseapp.com',
    storageBucket: 'foodmandu-a1c94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqIeJ7FD4V5VqZRWVySIqp17SUPbFWLi8',
    appId: '1:546013665087:android:942116f3f1bb7d0a5ba58a',
    messagingSenderId: '546013665087',
    projectId: 'foodmandu-a1c94',
    storageBucket: 'foodmandu-a1c94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3NaOEcWneY8v-ACGW_VGU9fx6sjrvKGE',
    appId: '1:546013665087:ios:cc0a253070dd59435ba58a',
    messagingSenderId: '546013665087',
    projectId: 'foodmandu-a1c94',
    storageBucket: 'foodmandu-a1c94.appspot.com',
    iosClientId: '546013665087-p9mmeujd0d2ths5vo5t8jotnpktmdlc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodmandu',
  );
}
